In [2]:
import numpy as np

*Numpy Axis*

In [3]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
x = np.array(x)

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x.sum(axis=0)

array([12, 15, 18])

In [10]:
x.sum(axis=1)

array([ 6, 15, 24])

In [11]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [13]:
x.ndim

2

In [14]:
x.size

9

In [15]:
x.nbytes

72

In [16]:
one = np.array([1,2,3,4])

In [17]:
one.argmax()

np.int64(3)

In [18]:
one.argmin()

np.int64(0)

In [19]:
one.argsort()

array([0, 1, 2, 3])

In [20]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x.argmin()

np.int64(0)

In [22]:
x.argmax()

np.int64(8)

In [23]:
x.argmax(axis=0)

array([2, 2, 2])

In [24]:
x.argmax(axis=1)

array([2, 2, 2])

In [25]:
x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [26]:
x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [27]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
x2 = [[1,2,3], [4,5,6], [7,8,9]]

In [30]:
x + x2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
x/x2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
x*x2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [33]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [34]:
x.sum()

np.int64(45)

In [35]:
x.max()

np.int64(9)

In [36]:
x.min()

np.int64(1)

In [37]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.where(x>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [39]:
np.count_nonzero(x)

9

In [40]:
np.nonzero(x)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [41]:
import sys

In [42]:
parr = [1,2,3,4]

In [43]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
sys.getsizeof(1) * len(parr)

112

In [45]:
x.itemsize * x.size

72

In [46]:
x.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

*Explore methods , functions and attributes in Official Documents*